### ISSUE TITLE
Thoughts on a "ies_prior_scale_fac" type variable?

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#118]
I have convinced myself I'd like my reals drawn from one parcov (e.g. "tight") and my parameter upgrades scaled, but "not that much." It seems to me the variable "ies_use_prior_scaling(False)" could be seen as implicitly scaling (pi - pm) by 1. So maybe just a linear interpolation of the scaling factor between no scaling and scaling by full std?

scaling = (1-std)*sf+std

where sf is the new variable ranging from 0 to 1, resulting in full std scaling to no scaling, respectively.

**Comment by jtwhite79** [comment]
I think with the "full solution" (use approx = False), the lambda is a scalar multiple of the prior cov matrix so you can use lambda as that factor more-or-less -that scaling is more about keeping parameter changes in harmony with prior (so that really uncertain pars are allowed to change more than parameters that are informed thru the prior) . I guess you could generate an ensemble using a large par sigma range and then pass that ensemble to ies with par sigma range decreased to achieve a more tightly clustered prior ensemble that is not subject to the same level of prior enforcement. Is that what you are looking for?

**Comment by wkitlasten** [comment]
First, I assume "really uncertain pars are allowed to change more than parameters that are informed thru the prior" is invertible:

"really certain pars are allowed to change less than parameters that are not informed thru the prior"

As I understand it, using lambda along with prior scaling essentially scales all prior_std the same (scaling = lambda*prior_std). Not using prior scaling is essentially saying prior_std = 1 and all terms are scaled the same (scaling = lambda), right? What if we had something in between, a vector of scaling factors between prior_std and 1 for each par that still restricts really certain pars from changing as much as less certain pars, but not as extreme as full parcov scaling.

For example, my proposed sf_var of 0.5 would scale [par0, par1, par2] by [3, 1.5, 0.55] rather than the std = [5, 2, 0.1]. As sf_var approaches 0, you have "use_prior_scaling(True)." As sf_var approaches 1 you have the default "use_prior_scaling(False)." Anything in between provides subdued parameter specific scaling still influenced by prior_std. Just quarantine induced madness perhaps... as if there aren't enough knobs to tweak anyway!!

![image](https://user-images.githubusercontent.com/14982084/106074311-86290a00-6170-11eb-9ab4-2b53f1e5fac0.png)

**Comment by jtwhite79** [comment]
@wkitlasten - Im gonna close this issue just for book keeping purposes.  let us know if you have more thoughts on this...
