### ISSUE TITLE
Incorrectly reading secondary text marker in instruction files

### ISSUE THREAD

**Issue by kyledavis-usgs** [usgs/pestpp#13]
The instruction files don't seem to be correctly reading output files using the secondary text marker.

We're using MODFLOW 6.0.4 and utilizing the built-in observation utility. For example, MODFLOW generates streamflow results from one or more observations in the SFR package. MODFLOW 6.0.4 uses non-advancing output instead of fixed length strings, and the outputs are comma separated but do not contain spaces between observation values. Vanilla PEST 16.1 and BeoPEST 16.1 will correctly read the instruction set and parse output values using a secondary text marker, but PEST++ doesn't seem to be locating the secondary text marker in the output observation file. In the past, we've been able to use the whitespace delimiter in our instruction file because the outputs were comma separated with spaces between values. I've included examples of working and non-working output file and instruction file. 

Examples:
pre-MODFLOW 6.0.4 SFR observation output file:
> time,SEEPAGE_FLUX1,SEEPAGE_FLUX2,SEEPAGE_FLUX3
>  1.000000000000,  1962323.838381852,  1962323.838381852,  1962323.838381852
>  32.00000000000,  1012443.579448908,  1012443.579448908,  1012443.579448908

working instruction file:
> pif $
> $time,$
> l1 w w !obs1_1! w !obs2_1! w !obs3_1!
> l1 w w !obs1_2! w !obs2_2! w !obs3_2!

MODFLOW 6.0.4 SFR observation output file:
> time,SEEPAGE_FLUX1,SEEPAGE_FLUX2,SEEPAGE_FLUX3
>  1.000000000000,1962323.838381852,1962323.838381852,1962323.838381852
>  32.00000000000,1012443.579448908,1012443.579448908,1012443.579448908

non-working instruction file:
> pif $
> $time,$
> l1 $,$ !obs1_1! $,$ !obs2_1! $,$ !obs3_1!
> l1 $,$ !obs1_2! $,$ !obs2_2! $,$ !obs3_2!

**Comment by jwhite-usgs** [comment]
Hey Kyle - thanks for the heads.  You are correct, there is an issue.  Debugging now...wading through a sea of goto statements!

**Comment by kyledavis-usgs** [comment]
Thanks Jeremy. I should have submitted this issue a long time ago. I noticed it maybe 6-12 months ago with other types of MF output that were comma separated without spaces. But I was able to get around it by running a small python script to read in the comma separated file and spit out a tab separated file. But I figured you'd like pest++ to operate in much of the same way as vanilla pest--so I figured you'd like to know that this functionality didn't appear to be working.

**Comment by jwhite-usgs** [comment]
Ok @kyledavis-usgs - should be fixed as of version 4.2.12 (the latest version on the master branch) - sorry for the delay - I got forced to update visual studio which then forced an update of the intel compilers - BARF! Anyway, there was an issue in the fortran MIO module (from @doherty1234 ) when parsing model output lines that have free format obs - the function `getnxt()` looks for the next space in the line, which bombs in your case - I think this had already come up in PEST and INSCHEK b/c there was a special conditional to also look for commas in addition to spaces, so I just replicated this behavior.  This isnt the perfect fix since someone might also use a single char secondary marker other than the comma - working with J Doh about how we should handle this moving forward.  

Please don't hesitate to report to any issues with pest++!

**Comment by kyledavis-usgs** [comment]
@jtwhite79 it does appear that the issue has been taken care of for our case. I'll certainly continue to work with PEST++ and let you know if any other issues arise!
