### ISSUE TITLE
Counter for autoadaloc?

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#166]
How hard would it be to report as each of the circular-shift calcs finish (or start) for the autoadaptive localization (to the rec or the screen or both)? It is hard to get a feel for how long the process is going to take or how far along it is. It would be nice to get a feel for how expensive it is as npars, nobs, and nreals change with each problem.

**Comment by wkitlasten** [comment]
Also, <random late night though>... any thoughts on how a "subset" approach might work with autoadaloc?

**Comment by jtwhite79** [comment]
Can def make that reporting happen.

On the subset with localization.  The two are independent in that the localizer gets fed to the solve for each lambda but then the subset is just a hack to save runs.  What were you thinking re subset?

**Comment by wkitlasten** [comment]
I'm just thinking (if you can call it that) the "background correlations" might be revealed in fewer circular shifts. So do less than N-1 circular-shifts. New arg similar to nsubsets, but independent. Just base the autoadaloc calcs on P circular-shifts, rather than N-1.

**Comment by jtwhite79** [comment]
Oh I see.  That's a good idea - I'll add that option.

**Comment by BJEANNOT0** [comment]
Hello,

I write to give a thumbs up to the idea from wkitlasten  : the autoadaloc on P circular shifts instead of N-1 would be great indeed to be able to benefit both from a very high amount of realizations AND localization at the same time. Right now, if I have a lot of realizations, localization takes a big amount of time and can sometimes induce segmentaiton faults because of memory issues.

Other idea : would it be possible to use the agents to make the localization ? I think they are idle at the time the manager works on the localization process. Being able to use the cores of the agents during localization would enable to remove the current limitation of multithreading for localization which is that the maximum number of threads must be lower than the number of cores on the machine thats hosts the manager.

Best regards,

**Comment by wkitlasten** [comment]
@BJEANNOT0, upon further investigation, I don't think the "fewer circular shifts" will help much. Most of the computational effort appears to be in the numerous "local" parameter upgrade calculations that result from the AAL. @jtwhite79 mentioned working on a way to farm out the upgrade calcs to the workers, but I'm not sure what the status of that is and it is far beyond my ability to grok (grokability)! Another thought might be to do some sort of "post AAL grouping" before solving (PCA or something?)... but that's just another wobbly thought and my brief, cursory investigations fell flat. Someone smart like @mnfienen might be able to come up with something though.
