### ISSUE TITLE
Question concerning ies_subset_size()

### ISSUE THREAD

**Issue by nikobenho** [usgs/pestpp#177]
As the title says this is more of a question than an issue.

I would just like to ask what the implications are for choosing a larger subset size is, and if there is a practical upper limit? Say, for example, I use an HPC with 20 cores on the node running ies in manager mode, would I be able to select a subset size of 20 without incurring extra run-time (i've set ies_num_threads() to 20), and would this result in faster convergence?

Cheers

**Comment by wkitlasten** [comment]
@nikobenho , it is my impression that it doesn't seem to make much difference in the long run (at least in the few models I have explored). That said, I usually aim to get the number of "upgrade ensemble" runs approximately equal to the "remaining ensemble" runs because if I am going to tie up those nodes with a job I might as well use them. Of course, that depends on the lambda mult and scale parameters you use. Also note, a negative value translates into a % of nreals, so nreals = 100 and subset size = -10 will use a subset of 10, which results in 90 "upgrade ensemble" runs if you are using the default lambda mult and scale values.

**Comment by jtwhite79** [comment]
FWIW I also try to balance the number of upgrade runs with number of workers and also like the percentage based subset size.  As with so many other things in the data assimilation world, the subset is a shortcut and there are very very few shortcuts without penalty.  The issue is that the subset might lead to selecting a suboptimal upgrade (lambda and scale factor) because the subset didn't represent the performance of the full ensemble.   If you are concerned with this issue, then increase the subset size...you can also play with the number of lambda multipliers and or number of scale factors to accolade a larger subset size while keeping number runs in check.

**Comment by BJEANNOT0** [comment]
Hello,

following your last message @jtwhite79, if I have an enormous amount of workers available (more workers than parameters to adjust and also more workers than the number of realizations), do you think that increasing the subset size to 100% of the active realizations would be a good idea ? Will this spend any more time ?I fear that there might be a bottleneck in the calculations that is not computed in parallel. I emphasize that I deal with a model with several hundred thousands observations and hundreds of parameters. It may be a memory problem for the manager if I try to fill all the jacobians i guess ?

Thank you for your help.

ALso, how do you set the subset size in "percentage based" mode ? I did not see the option of ies_subset_how that would allow me to do it. Thank you  again.

Best regards,

**Comment by jtwhite79** [comment]
the number of runs used for upgrade testing is `len(ies_lambda_mults)` X `len(lambda_scale_fac)` X `ies_subset_size`.  So if you make the subset size >= num_reals, then you will incur a lot more runs for testing unless you reduce those two lambda vectors.  By default, there are 4 lambda mults, 3 scale factors and 4 subset reals, so 36 runs for upgrade testing.  If you use 100 realizations and no subset, this number becomes 1200 runs for upgrade testing.    If you increase the subset size, that should in theory help to better identify the optimal upgrade ensemble to use (using just 4 reals for the subset size is probably the minimum, but its very efficient).  I think probably using 25% of the ensemble would be a nice compromise if you have lots of workers (`ies_subset_size(-25)` is how you would get 25% of the num reals as a subset)

without localization, the ies upgrade calculation should only be a few seconds to minutes even for millions of pars - the bottleneck in the solution process is an SVD on matrix that is num_reals X non-zero weighted obs.  So if you have a huge number of non-zero weighted obs, this could be a little slower.   Still should be pretty quick. 

You are correct re number of threads - that is only used for the localized solve. 

If I had a huge number of workers available, I would increase the number of realizations to 1,000 and use  `ies_subset_size(-10)` to `ies_subset_size(-25)`.  More realizations is always better in ensemble methods...

**Comment by BJEANNOT0** [comment]
Thank you very much.

**Comment by nikobenho** [comment]
Thank you all for your commenting. This is of great help for me when setting up the HPC runs. 
Cheers.
