### ISSUE TITLE
derinclb for log-transformed parameters

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#187]
Hi,

i have a question about derinclb.
If my parameter is log-transformed, does derinclb pertain to the value of that parameter or to the log-transformed value of that parameter ?
 Also, I see that the documentation says this :" If a parameter is log-transformed then it is wise that its increment be calculated using the “relative” method, though programs of the PEST++ suite do not insist on this.". Building on this, do you advise against using derinclb for log-transformed parameters ?
Thank you for your help.
Best regards,

**Comment by jtwhite79** [comment]
You are quickly reaching the limits of my understanding with all these derivative options!  I think you almost always want to have a `derinclb` set because it keeps the denominator from getting so small that the resulting derivatives are just numerical noise. 

I don't want to steer you away from pest++ but pest_hp has all of the derivative-based jacobian and associated regularized parameter estimation stuff nailed...and as long as you par names <= 12 chars and obs names <= 20 chars, you should be able to move freely between pest_hp and pest++...

**Comment by BJEANNOT0** [comment]
Thank you for your answer.
Best regards,
