### ISSUE TITLE
new control file format

### ISSUE THREAD

**Issue by jtwhite79** [usgs/pestpp#19]
I want to have this discussion here so everyone is aware of how things went down.  So far, @doherty1234 and I have had some discussions that have led to the attached control file format.  Important bits:
- retain the "* -section-" format.
- "control data" can now be "control data keyword" which then makes this section a keywork-value style (whitespace sep).  All of the control data args will have predefined internal default values so only changes from the defaults need to be specified.  This keyword section is also be the home for svd, regularization, pareto and ++ args.
- all repeatable sections can now be in external csv files.  these files must have a header and that header must have at least the variables that each calling program needs to run (e.g. parnme, parval1, parubnd, etc).  it can have extra columns (x,y,z,time,etc) but those are ignored unless the calling program needs them.  might need to add parsing args such as what values represent missing values, etc
- dimensioning counters are no longer needed
- parameter groups and observation groups are now optional (parameter group defaults will also be internal) 
- section order doesn't matter
- tied parameters will be handled in the standard parameter data csv file (instead of listed at the end of the parameter data section)
- if an unrecognized "* -section-" is encountered, the calling program should ignore it
- comment lines start with '#', blank lines are fine
- split model input/output section into two sections: model input and model output

One item that could use some discussion: should we define and use more common variable names?  so "name", "upper_bound", "value" instead of "parnme"/"obsnme", "parubnd","parval1"? 

This is all up for discussion!

[new_pst.zip](https://github.com/usgs/pestpp/files/3429609/new_pst.zip)

**Comment by damianmerrick** [comment]
Looks good! Love the removal of dimensioning counters. So will each observation group be defined implicitly just by its use with one or more observation?

My 2c...

- Consider an optional mechanism for the external csv loads to map between csv field names and pest parameter names. Something like `external filename.csv csvfieldname1=>parlbnd csvfieldname2=>parubnd`. Or optional mapping specifications that are fleshed out in their own section and are then referenced by an external statement. These would allow a bit more flexibility in construction and use of csvs, e.g. you could have a table with two sets of parameter min/max ranges and switch between them just by changing the mapping in the control file, or use a csv output directly from another utility without having to rewrite it with pest parameter names.
- Re: more common variable names, this would be nice, though some of us are so used to the old names it would take some getting used to. Perhaps it's worth supporting pre-defined synonyms for the same variable, e.g. use either "upper_bound" or "parubnd" interchangeably?

**Comment by mnfienen** [comment]
A couple thoughts:

- I agree with @damianmerrick that new names would be nice but that should probably still support the old ones. Also agree that losing the dimensional counters gets a thumbs up!
- love having comments and blank lines support continuing
- I prefer at least a warning (if not an error) for invalid "* -section-" being encountered. I fear just skipping them could lead to people not knowing that their input is being ignored in some cases. Please don't fail quietly or ignore without at least a warning
- also thumbs up for the extra columns! This would help with backward compatibility by being able to use short names but still have important related metadata available for postprocessing, etc.

**Comment by jtwhite79** [comment]
Thanks @damianmerrick and @mnfienen .  I like the idea of setting synonyms for the variable names.  And def dont want to fail silently.  Maybe different codes wont need additional "*" sections?  I think with control data keyword and moving SVD, reg and ++ args into control data keyword, that will be the home for all algorithmic controls (of which, unused will be reported/warned).  I like the idea of the optional mapping to columns, but Im tempted to hold off on that until we get the synonym deal worked out - is that ok @damianmerrick ?

**Comment by damianmerrick** [comment]
Sure, no big deal on the column mapping @jtwhite79 - just something to keep in mind as a possible extension for later.

**Comment by MJKnowling** [comment]
All looks great to me. Agree re fail visibility and importance of echoing defaults as these defaults may change over time. I especially dig that all alg controls used for diff pest modes/across diff pestpp tools are contained in one section. Do we need a pcf version declaration? This could be triggered by e.g., "* control data keyword".

**Comment by briochh** [comment]
@jtwhite79, I like the sound of these proposed structural developments. Defo agree regarding having warnings for unexpected "* -section-" (as someone who has a solid track record for typos).
On the face of it, external files for scetions sounds great and should make setup easier. For the script-based PEST setups we will need to be carefull with tracking those relative paths for external files. Could see a scenario where (due to a bit of sloppyness) users call old or obselete external files. Actually, this would be a danger for all users (imagining directories with `par_data.csv`, `par_data_copy1.csv` ... `par_data_copyn.csv` helishness). Ultimately the user holds the responsibilty for making sure the correct external files are read - but should make sure potential mistakes are easy to catch.

**Comment by jwhite-usgs** [comment]
@MJKnowling - wasn't sure about the version tag either.  I thought it would be better to be explicit, but could easily go without too

@briochh - agree RE pathing - Im also really good at messing that up!  Just thinking about this but maybe we could optionally have pyemu add datetime stamps to the external csv filenames - this might be nice for several reasons...

**Comment by doherty1234** [comment]
Here are some of my thoughts. I am sorry for the delay. I have had to write a few lengthy documents over the last few days.
It all looks good to me. I am not sure how much of this I can support because of all the things that I will need to attend to over the next few years with the new GMDSI project. But as long as there is backwards compatibility, we will be fine. I will definitely support the use of CSV files for parameters and observations so that others can introduce tags to these files for visualization purposes etc.
Jeremy, can you provide an example of how tied parameters are done? I did not see this in test.par_data.csv.
Default values. I agree that these should be echoed to the run record file. I guess that this is the responsibility of those who write the programs – but it is definitely a good idea. 
Regarding extra sections in the PEST control file. I have some extra sections in PEST_HP – e.g. for randomized Jacobian and distribution of files. The same applies to a new program that I am working on that does “realization space inversion” – a bit like PESTPP-IES.  Perhaps you are right in that all control keywords should be in the new “control data keyword” section. And indeed, this is what I will do if I get around to supporting keywords in PEST. In the meantime, I think that for PEST and PEST++ to be interchangeable, then any program in these suites should expect to encounter a section of any name. It just ignores it if it does not recognize it. Mike does not like this, and I understand why. (I am also obsessed with catching errors.) Perhaps this should not be part of the specifications but can be something that a program author can include if he/she wants to. 
Perhaps a warning is fine. But this means that if someone adds a new section (for tabulated variables) in a new PEST or PEST++ program, then older programs will forever be issuing warnings. There is a kind of built-in obsolescence here. But no big deal. 
I am not sure that we need “version=2” at the top of the new PEST control file. A problem is – what does this imply? As stated above, I will not have the time to implement all of these new protocols. Thus I may not support keywords for a while (sadly). But the support or otherwise of keywords is taken care of with the “keywords” indicator next to “control data”. 
Now the absence of keywords does not determine whether NPAR and NOBS have any meaning. PEST++ does not use these right now, I believe. I still do (to dimension arrays ahead of time). This might just be one of those things that a user needs to be aware of. That is, if you are using PEST, you’d better get these right. Not so with PEST++. And, of course, they are omitted (or ignored) if the “keyword” option is used.
A reader is directed to CSV files through “external” on the first line of the respective section. The only cause for confusion here is if “external” is the name of the first parameter (or whatever) in a non-CSV file option. I guess the giveaway is that if the rest of the line is illegal, then “external” means “external file”. Or should we have a tag that is less likely to be misunderstood – such as “open/close” as in MODFLOW, or “protocol=external” – something like that?  Or should “external” be placed on the same line as the section header? E.g. “parameter data external” (similar to “control data keyword”?
So do we need “version=2”? I am thinking not because it is redundant.
I like Damien’s idea of column mapping – not so much for myself as for others. Anyway, it is up to you, Jeremy, whether that is for now or later.
I do not have any other comments really.
Thanks

**Comment by jwhite-usgs** [comment]
Thanks @doherty1234 - I agree with the confusion over `external` and I like the idea of moving the external keyword up to the section marker: `* parameter data external` and `* observation data external`.  I think that will make it easier to decide how to process each section.  And let's drop the `version=2` tag on the first line.  Any objections?

**Comment by e-desousa** [comment]
Hi guys,

It is looking good. A few things that might be handy:

1 - For tied parameters, could we set the reference parameter name as an extra column, instead of putting a list at the end of the parameter section?
2 - Could we use tab-delimited fields on the external files, in a addition to comma separated?
3 - Support for transposed format on the parameters (especially for IES ensembles)?

**Comment by jwhite-usgs** [comment]
Thanks @e-desousa.  
1 - I was thinking the same for the reference parameter info - I'll use `partied` as the formal column name (still need to work out some more common variable aliases).  
2 - I think we could support whitespace delim but I pretty sure that would also require an explicit "missing_value" arg along with the filename.  I suspect recognizing and handling missing values in the columns of these external files will be important (since not all parameter will have x,y,z,time, etc).  But I think between comma-sep and whitespace-sep, we can cover most use cases.
3 - support for transposed ensemble I/O should be covered by the `++ies_csv_by_reals`` arg.  Is that what you are looking for?

**Comment by siadicus** [comment]
Reading through this, nodding my head to everything, and after some thinking, I have very little to add really, other than some general comments. Time to get into some programming and see how this'll work! 

1 - From the perspective of development (using the FORTRAN interface to PEST++), I'm real stoked about the external files for parameters and observations, as other algorithms (e.g., PSO) will often require additional/different algorithm-specific control data for parameters/decision-variables. From the user perspective, being able to add metadata, etc., is huge. I like it!

2 - The "* control data keyword" section will be massive for users and developers alike. @jtwhite79  you mentioned that the keyword section could allow for unused keywords that are reported/warned - sounds good to me! 

In theory, it seems to me that between the external files and flexibility in keyword usage, users could potentially interchangeably use the same control file for multiple calling programs and PEST utilities (e.g., PESTCHEK). This is pretty cool. And, with these two features, I agree that the development of new calling programs could theoretically be setup to run without the need for any non-standard, calling-program-specific "* sections".

**Comment by wkitlasten** [comment]
Cool. I agree with everything I think I understand.

To deal with the field name issue (and working off of what others have said), couldn't the file name simply be followed by an ordered list of white space delim alternative names, or blank if using defaults from manual? So below pest would use the defaults for myfile1.csv and those provided for myfile2.csv. Seems like the least amount of work, but maybe I'm thinking too simply.

* parameter data
myfile1.csv    
myfile2.csv  PARNAME TRANS CHGLIM VAL1 LOWER UPPER PARGP SCALE OFFSET DERCOM
...

**Comment by cmuffels** [comment]
1. looks good jeremy
2. i like the idea of a warning for unknown sections. error may be harsh - this is what modflow did for unknown packages in 200X. a person cannot create their own package type as a result. modflow-usg warns and ignores the PATH package type i added for my particle tracker. much easier for me to maintain my "value added" code as a result.
3. associating params and obs with widely used spatial files is important and i can see how to do it with this format, so that is great. straightforward to script addition of attributes to a shapefile or the like with parameter values or residuals from output directly without an interim mapping file.

**Comment by mnfienen** [comment]
This is all sounding really good. I would echo @cmuffels in that unknown sections should generate a warning but not an error for flexibility (but also to help catch typos and such errors).

**Comment by jwhite-usgs** [comment]
[draft_control_file_format_spec.pdf](https://github.com/usgs/pestpp/files/3478956/draft_control_file_format_spec.pdf)

Thanks for everyone's input - really appreciate it!  Ive compiled this discussion into the attached draft format specification (very informal).  Im planning to start chipping away at this ASAP but will realistically be a few months before its implemented and tested.  If anyone has any additional thoughts, please keep the discussion going (or there needs to be revisions to the draft spec).

**Comment by wkitlasten** [comment]
"Parameter and observation names less than 201"

Awesome!

**Comment by jwhite-usgs** [comment]
@wkitlasten - the 200 char par and obs names is already in PEST++.  Its all backward compatible: If you go over 12/20 chars for par/obs names, then you get the extended JCO file format, if you stay under 12/20, you get the standard JCO file format.  easy as!

**Comment by jwhite-usgs** [comment]
The new control file format is now available!
