### ISSUE TITLE
Non enforced parameter bounds with tie_by_group(true)

### ISSUE THREAD

**Issue by kyledavis-usgs** [usgs/pestpp#21]
It appears that the parameter bounds are not being strictly enforced when `tie_by_group` is set to true with ipestpp-sen.exe (I am not sure about the other executables)

**Comment by jwhite-usgs** [comment]
thanks @kyledavis-usgs .  This is an issue, not just for `tie_by_groups` but for parameter tying in general.  working on a fix now...

**Comment by jwhite-usgs** [comment]
alright @kyledavis-usgs there is now (4.2.14) an option to cover this use case: `enforce_tie_bounds` - False by default. .  Note PEST does not enforce tied par bounds but I can see where it would be nice to have that option.  Just have to be careful because this option can yield narrower effective bounds for adjustable parameters.

**Comment by kyledavis-usgs** [comment]
Thanks @jwhite-usgs I'll try out this option soon!

**Comment by kyledavis-usgs** [comment]
@jwhite-usgs should the keyword be `enforce_tied_bounds` and not `enforce_tie_bounds`?

**Comment by jwhite-usgs** [comment]
doh!  yes `++enforce_tied_bounds`
