### ISSUE TITLE
Option to write simulation results as they finish?

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#23]
It would be useful for me to check results from simulations as they finish, rather than wait for the entire batch (ensemble) to finish. Unfortunately I either run a small ensemble, or wait for all the simulations to finish (usually 1 or 2 stragglers!) before I can explore the results. I assume this is a run manager issue. Not sure if it is possible or how much pain is involved in writing a temp file or appending the .csv as the results come in, or if there is already an option and I am missing it.

**Comment by jtwhite79** [comment]
When using the panther run mgr, there is a run storage file that is filled as runs complete - you’ve probably seen the huge .rns file after a run.  If you are careful, I think you can read it even while pestpp has it open for writing.  Pyemu has some support for reading this file.  Otherwise, we have wait until the whole batch of runs Is processed by the run mgr.

**Comment by wkitlasten** [comment]
Excellent! pyemu.utils.read_pestpp_runstorage() is exactly what I was looking for.
