### ISSUE TITLE
panther_agent_freeze_on_fail() 

### ISSUE THREAD

**Issue by borjav2** [usgs/pestpp#242]
Hi all,

When you use the command` panther_agent_freeze_on_fail(true) ` and an agent freezes, how can you unfreeze it? I tried restarting the agent using the following code but it spawns a new agent, pestpp-glm and python.exe processes.

Code:

`if rel_path is not None:
                exe_path = os.path.join(rel_path,exe_rel_path)
else:
                exe_path = exe_rel_path
            args = ["start", exe_path, pst_rel_path, "/r /h", tcp_arg]`

Hence, the command run by the cmd is: `start "pestpp-glm.exe" "case.pst" /r /h localhost:4004` 

Thanks in advance

**Comment by jtwhite79** [comment]
That `freeze_on_fail` stuff is really a debugging option so that you can better see what happened on (remote) worker if a run failed.  This gives you the opportunity to find the issue, potentially fix the issue, and then restart the full run (all the workers).  This means, as you may have found, that the frozen workers may persist even after the master has exited - this is bc I wanted to make sure those workers held their files exactly as they were for the failed run.  But this can cause the worker process to be "orphaned" if the master exits.

In this case, you have two options.  First, find the orphaned processes in task mgr/active process list and force-quit.  Or you can make a file in the directory of the worker that is frozen called "pest.stp" and put a "4" on the first line of this file.  Once you save that file with the "4", the frozen worker should pretty quickly unfreeze itself and then it will realize the master has exited and it will exit gracefully (in theory).  You can also use the standard IT approach and just restart your computer if have a heap of frozen workers! haha

**Comment by borjav2** [comment]
Thanks for the feedback! So some processes may become orphaned and you have to kill it using task administrator. Maybe knowing the process number of each agent would be helpful to erase a particular process and not another by mistake! This would be easily done with `p.pid` where p  is a sp.Popen object. Aaand Yes!, there's always the solution to restart your computer.
