### ISSUE TITLE
Failed partial update still reducing lambda?

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#249]
It appears pestpp-ies is trying to do a partial update even when no reals have reduced phi? The partial update does not "improve phi stats" (since no reals have a reduced phi), but lambda is updated (reduced). It continues and parameters never change.

Should lambda be increased if phi is the same before and after a partial update?

...current lambda:    1

  ---  evaluating upgrade ensembles  ---
...last mean:  20843
...last stdev:  36089.9

  ---  best subset mean phi  (33680.4) greater than acceptable phi : 21885.2  ---
...updating realizations with reduced phi
...current best mean phi (after updating reduced-phi reals):  20843

  ---  partial update improved phi stats, updating lambda to  0.075  ---
...returing to upgrade calculations...

version: 5.2.3
binary compiled on Apr 25 2023 at 15:17:25

**Comment by jtwhite79** [comment]
There is a ctrl argument call ies_accept_phi_fac and by default is 1.05, so that ies will tolerate small increases in phi as "successful" since in some cases this might help it deal with local minimima (at least that was thinking...).  So if the new mean objective function is equal to the last best mean, then this 1.05 value will make the new objective function mean appear better than the last best mean (and then trigger ies to reduce lambda).  Maybe this is what is happening here?

**Comment by wkitlasten** [comment]
Sounds likely and reasonable. Maybe a check for "number of realizations with reduced phi >0" is prudent?

(and now back to the elephint in the room... and why it isn't reducing)

**Comment by wkitlasten** [comment]
Verbose=4 results suggest number of reals with reduced phi wouldn't catch it anyway:

```
  ---  best subset mean phi  (1.07349e+07) greater than acceptable phi : 1.05636e+07  ---
...updating realizations with reduced phi
updating pe:oe real =0:0, current phi: new phi  =8.54654e+06:8.54654e+06
updating pe:oe real =9:9, current phi: new phi  =1.28507e+07:1.28507e+07
updating pe:oe real =16:16, current phi: new phi  =5.52236e+06:5.52236e+06
...
```

Oh well, clearly a special kind of problem on my end.
