### ISSUE TITLE
termination criteria in PESTPP-IES

### ISSUE THREAD

**Issue by flydream0428** [usgs/pestpp#35]
@jwhite-usgs There are a few types of objective functions in PESTPP. What's the difference between the measured and actual objective function? My guess is that the measured one doesn't take weight into account. If this is true, does it even consider the observations with zero weights? 
I also notice that the termination criteria is based on the measured or composite objective function. What is the reason for this? Isn't the actual one more reasonable to reflect the modeller's intention?

**Comment by jtwhite79** [comment]
The measurement objective function is computed using the observation values plus realizations of measurement noise  (def includes weights!) - this is important to account for this noise in the final (posterior) ensemble.  The composite objective function is measurement plus regularization penalty ( zero by default) and actual is the objective function against the actual observations (no noise) in the control file.  The composite is used for termination and lambda selection.  

The latest development version now includes a “no noise” option that make the measurement and actual objective functions one in the same - this helps when your weights are deisgned to balance the objective function rather than express measurement noise.

**Comment by flydream0428** [comment]
Is there any publications where I can find the equation for the composite objective function? I also found that the two objective functions are the same for the base case. I am wondering why? 
[flow_cali.zip](https://github.com/usgs/pestpp/files/4211469/flow_cali.zip)

.

**Comment by jwhite-usgs** [comment]
This should be more clear in the latest documentation - if not, let us know.
