### ISSUE TITLE
lambdas() and lambda_scale_fac() not considered for super parameter iterations ?

### ISSUE THREAD

**Issue by apryet** [usgs/pestpp#40]
With a highly-parameterized model presenting pretty noisy derivatives, I obtained great improvement when using numerous lambdas and scale factors with pestpp-glm 4.3.3. But when performing an SVD-assisted parameter estimation, it appears that options lambdas() and lambda_scale_fac() are not considered for super parameter iterations. However, they are appropriately considered for base parameter iterations. Is that on purpose ? 
Thank you for your reply !

**Comment by jtwhite79** [comment]
The `++lambdas()` option is still used for the super parameter iterations - if you are seeing something else, please post your record file -, but you are right that the `++lambda_scale_vec()` option has not yet been implemented for super parameter iterations.  Pull requests happily accepted!  Otherwise, I'll try to get this done before version 5 is released.

**Comment by apryet** [comment]
Indeed, I missed it but the `++lambdas()` option is taken into account for super parameter iterations. I would be happy to contribute to the implementation of the `++lambda_scale_fac()` but so far, my skills in C++ are not sufficient to suggest pull requests  ! Anyway, thanks for the quick reply !

**Comment by jtwhite79** [comment]
I think Ive got the `lambda_scale_fac` option added to the super par iters now on a branch Ive been working on. I'll try to get it merged into develop later today - version will be 4.3.7
