### ISSUE TITLE
Precompiled binaries for PESTPP-PSO

### ISSUE THREAD

**Issue by laat0003** [usgs/pestpp#73]
Hi,

I'm just wondering if there is supposed to be a precompiled binary for pestpp-pso in the latest release? I can see in the makefile that it is only created if a FORTRAN compiler is available. I downloaded both the win and iwin release yesterday and it is absent from both of them.

**Comment by jwhite-usgs** [comment]
I'm working to get the intel-compiled PESTPP-PSO win binary building, but some isues.  if I cant get it resolved in the next day or so, I'll manually compile windows intel PSO and post it to the 4.3.17 release.

@mwtoews - the cmake process using kitware ninja and icl/ifort dies trying to link pestpp-pso and it looks like its because the external run mgr wrapper functions (that live in the run mgr wrappers lib) have different naming - the pestpp-pso objects are looking for upper case, no underscore (e.g. `RMIF_RUN`) but the wrappers lib has lower case and following underscore (e.g. `rmif_run_`) - Im not sure if the case matters...Is there a way to easily fix this naming issue?

**Comment by mwtoews** [comment]
Probably the Fortran targets should be built if Fortran is available, e.g. for iwin but not win. These targets (or programs) are pestpp-pso and inschekpp.

According to [this thread](https://community.intel.com/t5/Intel-Fortran-Compiler/LNK2001-and-LNK2019-unresolved-external-symbols-Link-errors-in-a/td-p/798016), Intel Fortran on Windows creates global names `LIKE_THIS` instead of `like_this_`. I have a few fixes in #74 to try and address these issues.

**Comment by jwhite-usgs** [comment]
@laat0003  - just posted a pestpp-pso windows binary with release 4.3.19

**Comment by laat0003** [comment]
Many thanks for the update. Happy to close this.
