### ISSUE TITLE
External Parameter Input File

### ISSUE THREAD

**Issue by lboutin** [usgs/pestpp#79]
Not sure if this is the right way to submit a question, but hopefully it is!

Based on previous correspondence, you guys discussed having all parameters in an external file, I've tried it with the latest version 4.1.9, without success.  The documentation suggest it's possible but I'm seeking for confirmation.

Best regards,

Louis-Charles Boutin

![Capture2](https://user-images.githubusercontent.com/8027133/87614513-386e1800-c6de-11ea-9f23-743e063e651d.JPG)

![Capture](https://user-images.githubusercontent.com/8027133/87614423-01980200-c6de-11ea-8a07-31b7753d1464.JPG)

**Comment by jtwhite79** [comment]
@lboutin - this is the best way to ask pest++ questions! the external file stuff is fully fleshed out for the latest release (4.3.19) and is also documented in the users manual (in the “documentation” directory).  The way it worked out is to have a section called “* parameter data external” and then list the external file(s) on the lines that follow - the external files must have a header line and that header line must name the required section quantities, either using the formal variable names or through “simplified” alias names (like “upper_bound” rather than “parubnd” .  There is an example of this in the user manual section 4.18

**Comment by lboutin** [comment]
Right, I had fetch version 4.3.19, but wasn't searching for the right key word. Sorry about that.  I realized that I was using ipestpp-ies which is the version 4.1.9 while the pestpp-ies was version 4.3.16.

Out of curiosity, is there any plans on tackling the implementation of truncated plurigaussian models with pestpp-ies? 

Best regards,

LCB

**Comment by jtwhite79** [comment]
I’m def interested in truncated plurigaussian but have to admit I’m not familiar with the details.  Would it require modifications to pest++ or could it be handled externally (ensemble generation and then with in a pre-processing script at model run time)?

**Comment by lboutin** [comment]
I have to admit that I'm just starting reading on the subject, so I don't know exactly what would require to change, but I suspect pest++ would have to be modified.  Might be of interest to you: Oliver and Chen 2018 https://doi.org/10.1007/s11004-018-9753-y

**Comment by tushargoyal22** [comment]
Is there any support for Ubuntu or other unix systems to use these executables?

**Comment by jtwhite79** [comment]
@tushargoyal22 the pest++ tools can be compiled for linux/unix using the make or cmake - you'll need c++11 support and Ive found gcc >= 4.8 works.  You can also try the linux pre-compiled executables under releases - these seem to be relatively portable.
