### ISSUE TITLE
opt_std_weights option

### ISSUE THREAD

**Issue by laat0003** [usgs/pestpp#82]
Hi,

Does the opt_std_weights option also consider the notional calibration observation weights as standard deviations of their uncertainty? It isn't clear in the manual if this is an alternative to supplying a covariance matrix of the calibrated parameter uncertainties.

Cheers,

**Comment by jwhite-usgs** [comment]
Sorry this isnt more clear.  The `opt_std_weights` option implies that you have specified the standard deviations (these could be calculated off line with pyEMU/pest utils or from an ensemble) for the model-based constraints directly, that is, there is no need to undertake any FOSM or stack-based analyses to estimate these standard deviations. So if you specify `opt_std_weights`, then the FOSM and stack-based processes are skipped and the weights for model-based constraints are used directly in the chance  constraint process.

**Comment by laat0003** [comment]
No apologies necessary re clarity. All good. So then is use of the opt_std_weights option analogous to using a stack based approach with opt_recalc_chance_every(massive number)? Assuming the stack and the ensemble used to get the standard deviations for the opt_std_weights are the same.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by jtwhite79** [comment]
This is where it gets a little tricky.  If you pass opt_std_weights, that overrides the other fosm and stack chance options for the whole run.
  Now on the stack stuff, currently the stack-based chance constraints are “distribution free” in that we use the cdf of the constraint values in the stack to shift, rather than assuming Gaussian.  So if there is a long tail in one direction, that is represented in the risk shifted value.

**Comment by laat0003** [comment]
Got it. Thanks for the clarification and please keep up the awesome work!
