### ISSUE TITLE
Missing base in new 'obs+noise' ensemble?

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#91]
In the interest of efficiency, I am reusing a par ensemble (i.e. same prior) and associated obs ensemble from a previous run, but generating a new 'obs+noise' ensemble based on a new set of targets. The 'obs+noise' ensemble contains 'ies_num_reals' realizations, but no base even though the 'restart_obs_ensemble' and 'parameter_ensemble' have 'base' and 'ies_add_base' is left as the default 'true'. Several reals were dropped so there are fewer reals in the 'restart_obs_ensemble' than the 'parameter_ensemble' or the new 'obs+noise' ensemble

First a question: the 'obs+noise' are the targets in the control file plus noise, and NOT necessarily tied to the simulation results in the 'restart_obs_ensemble', right?

Is there a way to 'line up' the new 'obs+noise' ensemble with the restart 'restart_obs_ensemble'  and 'parameter_ensemble' to ensure they have the same number of reals and there is a 'base' real (i.e. no noise added to the new targets). My impression from what I have is that my 'base' real in the 'restart_obs_ensemble' and 'parameter_ensemble' will be associated with the nth entry in 'obs+noise', where n is the number of reals in the obs ensemble.

For now I will just not reuse the initial 'restart_obs_ensemble' and avoid this issue.

**Comment by jtwhite79** [comment]
The reason the "base" is not added to the obs+noise ensemble when restarting is because when restarting, we cant know what realizations may have failed previously - this is because ies doesnt require par and obs ensembles to use the same realization names.  But I can see the value in what you are trying to do - Ive done that before but used pyemu to generate the new noise ensemble and made sure to add the base realization in the right row. 

I'll work on adding support for this special case, which I think is: restarting with supplying the par and restart obs en, both of these having the "base" realization, not supplying obs+noise, and `ies_include_base(true)` .  Does that sound right?

**Comment by wkitlasten** [comment]
That sounds right. So I would generate the noise+obs outside of pest,
presumably the same size as the 'restart_obs_ensemble', and just replace
the appropriate row (always the last?) with a noise free obs vector? All
hail pyemu!

For my current runs it only takes a few minutes to initialize the par, obs,
and obs+noise ensembles from the default pest behavior, so I will just do
that for now. But I can see it becoming a bit of an issue with a bigger
model, so I will do as you suggest.

(I'm getting a bit of deja vu... sorry if I already pestered you with this
before!)

**Comment by jtwhite79** [comment]
ok, after checking this out in the code, turns out this situation is being handled already but the base is being added to the obs+noise AFTER the original obs+noise was saved to file so that's why it wasn't showing up in file.  This is good news from the algorithm standpoint since the "base" realization is being paired with the appropriate noiseless realization but its a bug that the obs+noise ensemble wasn't being saved when updated.  This will be fixed in 5.0.3

**Comment by wkitlasten** [comment]
I am using 5.0.3 compiled Oct 9 and the 'base' real does not appear to be in the obs+noise ensemble. The last real does not match the obs in the control file. Are you getting a 'base' real on your end?
